version: build {build}
image: Ubuntu
services:
- docker

branches:
  except:
  - gh-pages

environment:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
  GH_TOKEN:
    secure: dhFy1eZoqG4QPkKTuLFxix7QQMxaIyIpYjkvTU3CukYZz1CEOJeHfBSaT8tkPsGL

before_build:
  - sh: dotnet tool install -g nbgv
  - sh: export SEMVER=`nbgv get-version -v SemVer2`
  - ps: Update-AppveyorBuild -Version "$env:SEMVER ($env:APPVEYOR_BUILD_ID)"

build_script:
# - ps: '& $env:BUILD_SCRIPT -t pack -c Release -v "$env:SEMVER" /p:GhPages=true'
  - sh: docker run -v $APPVEYOR_BUILD_FOLDER:/src -w /src -e NUGET_PACKAGES:/src/.nuget mcr.microsoft.com/dotnet/core/sdk:2.2.105 ./build.sh -t pack -c Release -v $SEMVER

test_script:
  # Selenium tests don't run in the docker image
  - sh: ./build.sh -s -t test -c Release --push-tests https://ci.appveyor.com/api/testresults/mstest/$APPVEYOR_JOB_ID

# all builds on the AppVeyor NuGet feed
artifacts:
  - path: build/*.nupkg
    name: nuget

for:

# Publish pages to github.io only from master
- branches:
    only:
    - master
  on_success:
  - ps: .\tools\gh-pages.ps1 -env appveyor

cache:
- .nuget
